AllCops:
  TargetRubyVersion: 2.6

Layout/LineLength:
    Max: 1024

Metrics/MethodLength:
    Max: 25
    Exclude:
        - tests/**/*

Metrics/ClassLength:
    Max: 150
    Exclude:
        - tests/**/*

Naming/AccessorMethodName:
    Enabled: No

Metrics/ParameterLists:
    Max: 7
    
Metrics/AbcSize:
    Max: 30
    Exclude:
        - tests/**/*

Layout/EndOfLine:
    EnforcedStyle: lf

Lint/RaiseException:
    Enabled: true

Lint/StructNewOverride:
    Enabled: true 

Style/HashEachMethods:
    Enabled: true

Style/HashTransformKeys:
    Enabled: true 

Style/HashTransformValues:
    Enabled: true 
    
Style/RaiseArgs:
    EnforcedStyle: compact