AllCops:
  TargetRubyVersion: 2.6


Layout/LineLength:
    Max: 1024

Metrics/MethodLength:
    Max: 25

Metrics/ClassLength:
    Max: 150

Naming/AccessorMethodName:
    Enabled: No

Metrics/ParameterLists:
    Max: 7